Request to merge the multiple feature to the Math-Magicians site.
BonkeGcobo/math-magicians pull request #5
Opened 2022-01-26 06:44 UTC by BonkeGcobo

1) We added two extra pages Home page and Quote Page,
2) We made these pages follow a given path using Route.
3) We updated the calculator component

2022-01-26 07:18 UTC, DeliceLydia requested changes
## Hi @BonkeGcobo, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! Mejor highlights for your project:
- Followed git workflow
- No linter errors
- Application is working as expected


## Required Changes ♻️
_Check the comments under the review._

- [x] Remember to add live demo in the README
- [x] You repeated `getting started` part in your README
- [x] `Install` part you can add how to run the project locally I mean step `npm i`, `npm run start` etc



### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-26 07:18 UTC, DeliceLydia commented on src/components/Calculator.js
> +/* eslint-disable react/no-unescaped-entities */
- [ ] Consider solving `eslint` errors instead of disabling them because we use it to help us to write good and clean codes

2022-01-26 07:18 UTC, DeliceLydia commented on src/App.js
>  // eslint-disable-next-line react/prefer-stateless-function
- [ ] Same here

2022-01-27 07:31 UTC, Meltrust requested changes
Hi @BonkeGcobo, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## You didn't resolve some of the previous reviewer's eslint solving requirements.  I will explain to you how it can be done.  Please, go to my comments below 👇 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-27 07:31 UTC, Meltrust commented on src/App.js
>  }
- [ ] You didn't solve this eslint rule either.  In order to solve it, you need to drop the class component and replace it with a function component.  Function components are `easier`, and a lot less complicated.  

In order to rewrite a class component to a functional component, you need to do this:

1. Drop the `export default class App extends Component { ...` to simply `const App = () => {`
2. Drop the `render()` method.  No longer needed.
3. If they exist, drop all the `this` (you are no longer using a class).
4. If it exists, drop the constructor (you are no longer using a class).
5. Drop the `{Component}` import.  No longer needed.
6. For a default export, do it at the bottom of the file, not in the function itself (to be able to use arrow function syntax!).

Look:

![image](https://user-images.githubusercontent.com/57421823/151310948-875529aa-acc8-4767-ac73-e9b72efba804.png)

I hope this makes sense to you 👍 



![image](https://user-images.githubusercontent.com/57421823/151311355-a2e6442d-964c-4900-9273-bd1196711f40.png)

And the project should still work!!

Now that you know how, please kindly remove that `// eslint-disable.....`, make your class component a function, and watch how the problem is solved!  You have a functional component now! Those are simpler!!💪 💪

2022-01-27 08:31 UTC, BonkeGcobo commented on src/App.js
>  }
Thank you very much @Meltrust  for your review

2022-01-27 09:15 UTC, BonkeGcobo commented
Change the class components to functional componets

2022-01-27 09:35 UTC, elyor-doniyorov approved these changes
Hi @BonkeGcobo, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![Approved](https://user-images.githubusercontent.com/67087664/151332011-e4759031-04a1-4807-8e9b-93c4d559d0fe.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-27 09:36 UTC, merged